/**
 * packages/github/src/lib/pr-helpers.ts
 *
 * Pure helpers for generating GitHub PR titles and body text from factory
 * task metadata and body content.
 *
 * No filesystem access. Depends only on @devory/core types.
 *
 * All functions are deterministic and side-effect free so they can be tested
 * in isolation and composed into GitHub Actions, CLI commands, or UI flows.
 */

import type { TaskMeta } from "@devory/core";

// ---------------------------------------------------------------------------
// Conventional-commit type table (reused for PR titles)
// ---------------------------------------------------------------------------

const COMMIT_TYPE_MAP: Record<string, string> = {
  feature: "feat",
  feat: "feat",
  bugfix: "fix",
  bug: "fix",
  fix: "fix",
  refactor: "refactor",
  chore: "chore",
  documentation: "docs",
  docs: "docs",
  test: "test",
  tests: "test",
  perf: "perf",
  performance: "perf",
  subtask: "feat",
};

/** Map task type to a conventional-commit prefix. Defaults to "feat". */
export function commitType(taskType: string | undefined): string {
  const t = (taskType ?? "").toLowerCase().trim();
  return COMMIT_TYPE_MAP[t] ?? "feat";
}

/** Derive a short scope label. Priority: repo_area → lane → project → "core". */
export function taskScope(meta: Partial<TaskMeta>): string {
  const repoArea = typeof meta.repo_area === "string" ? meta.repo_area.trim() : "";
  const lane = typeof meta.lane === "string" ? meta.lane.trim() : "";
  const project = typeof meta.project === "string" ? meta.project.trim() : "";
  return repoArea || lane || project || "core";
}

// ---------------------------------------------------------------------------
// PR title
// ---------------------------------------------------------------------------

/**
 * Build a PR title in conventional-commit format:
 *   `<type>(<scope>): <task title>`
 *
 * Truncated to 72 characters to fit GitHub's recommended title length.
 */
export function buildPrTitle(meta: Partial<TaskMeta>): string {
  const type = commitType(typeof meta.type === "string" ? meta.type : undefined);
  const scope = taskScope(meta);
  const title = typeof meta.title === "string" ? meta.title.trim() : "(untitled)";
  const line = `${type}(${scope}): ${title}`;
  return line.length > 72 ? line.slice(0, 71) + "…" : line;
}

// ---------------------------------------------------------------------------
// PR body
// ---------------------------------------------------------------------------

export interface PrMetadata {
  title: string;
  body: string;
}

/**
 * Build a structured PR description from task metadata and task body text.
 *
 * The body follows GitHub's recommended PR template structure:
 *  - Summary section (task fields)
 *  - Context section (task body if present)
 *  - Verification checklist (from task's verification field)
 *  - Factory metadata footer
 */
export function buildPrBody(meta: Partial<TaskMeta>, taskBody: string): string {
  const lines: string[] = [];

  // ── Summary ─────────────────────────────────────────────────────────────
  lines.push("## Summary", "");
  lines.push(`- **Task:** ${meta.id ?? "(unknown)"} — ${meta.title ?? "(untitled)"}`);
  lines.push(`- **Project:** ${meta.project ?? "(unknown)"}`);
  lines.push(`- **Type:** ${meta.type ?? "feature"}`);
  lines.push(`- **Priority:** ${meta.priority ?? "medium"}`);
  lines.push(`- **Agent:** ${meta.agent ?? "(none)"}`);

  const deps = Array.isArray(meta.depends_on) ? meta.depends_on : [];
  if (deps.length > 0) {
    lines.push(`- **Depends on:** ${deps.join(", ")}`);
  }
  lines.push("");

  // ── Context ──────────────────────────────────────────────────────────────
  const trimmedBody = (taskBody ?? "").trim();
  if (trimmedBody) {
    lines.push("## Context", "");
    // Include up to ~30 lines of the task body to keep the PR description focused
    const bodyLines = trimmedBody.split("\n").slice(0, 30);
    lines.push(...bodyLines);
    lines.push("");
  }

  // ── Verification ──────────────────────────────────────────────────────────
  const verification = Array.isArray(meta.verification) ? meta.verification : [];
  if (verification.length > 0) {
    lines.push("## Verification", "");
    for (const cmd of verification) {
      lines.push(`- [ ] \`${cmd}\``);
    }
    lines.push("");
  }

  // ── Footer ───────────────────────────────────────────────────────────────
  lines.push("---");
  lines.push("*Generated by Devory · ai-dev-factory — human review required before merge.*");

  return lines.join("\n");
}

/**
 * Build a complete PR metadata object (title + body) from task metadata.
 */
export function buildPrMetadata(
  meta: Partial<TaskMeta>,
  taskBody: string
): PrMetadata {
  return {
    title: buildPrTitle(meta),
    body: buildPrBody(meta, taskBody),
  };
}
